#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = BigElephant\XfConsole\Application::start(null);

$app->detectXenForo();

$app->runCommanders(
	new BigElephant\XfTools\ToolsCommander,
	new BigElephant\XfFiles\FilesCommander
);

$app->run();